# Generated by Django 2.2.2 on 2019-06-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('awarded_for', models.CharField(max_length=255)),
                ('first_awarded', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Award Categories',
                'db_table': 'tv_award_categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'tv_cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('code', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'tv_countries',
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('founded', models.DateField(blank=True)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tv.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tv.Country')),
            ],
            options={
                'verbose_name_plural': 'Festivals',
                'db_table': 'tv_festivals',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Genres',
                'db_table': 'tv_genres',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('code', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Languages',
                'db_table': 'tv_languages',
            },
        ),
        migrations.CreateModel(
            name='MovieTVShowCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Movie TV Shows Categories',
                'db_table': 'tv_movies_tvshows_categories',
            },
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Person Roles',
                'db_table': 'tv_person_roles',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('birth_date', models.DateField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/people/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tv.Country')),
                ('person_role', models.ManyToManyField(to='tv.PersonRole')),
            ],
            options={
                'verbose_name_plural': 'People',
                'db_table': 'tv_people',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('abbreviation', models.CharField(max_length=10)),
                ('formation', models.PositiveIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tv.Country')),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'db_table': 'tv_organizations',
            },
        ),
        migrations.CreateModel(
            name='MovieTVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_es', models.CharField(max_length=255, verbose_name='Spanish Latin America')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('release_date', models.DateField(blank=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('running_time', models.PositiveIntegerField(blank=True)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('trailer_url', models.URLField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/movie_tvshows/')),
                ('award_category', models.ManyToManyField(blank=True, to='tv.AwardCategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tv.MovieTVShowCategory')),
                ('country', models.ManyToManyField(to='tv.Country')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tv.Person')),
                ('festival', models.ManyToManyField(blank=True, to='tv.Festival')),
                ('genre', models.ManyToManyField(to='tv.Genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tv.Language')),
            ],
            options={
                'verbose_name_plural': 'Movies TV Shows',
                'db_table': 'tv_movies_tvshows',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv.Country'),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('formation', models.PositiveIntegerField()),
                ('website', models.URLField(blank=True, max_length=255)),
                ('category', models.ManyToManyField(to='tv.AwardCategory')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tv.Country')),
                ('presented_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tv.Organization')),
            ],
            options={
                'verbose_name_plural': 'Awards',
                'db_table': 'tv_awards',
            },
        ),
    ]
