# Generated by Django 2.2.2 on 2019-06-18 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_auto_20190618_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='awardcategory',
            name='first_awarded',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='formation',
        ),
        migrations.AddField(
            model_name='award',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awardcategory',
            name='first_awarded_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movietvshow',
            name='no_seasons',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='organization',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movietvshow',
            name='running_time',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
