# Generated by Django 2.2.2 on 2019-06-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0005_auto_20190618_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietvshow',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
