# Generated by Django 2.2.2 on 2019-06-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0006_auto_20190618_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietvshow',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Spanish Latin America'),
        ),
        migrations.AlterField(
            model_name='movietvshow',
            name='no_seasons',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
