# Generated by Django 2.2.2 on 2019-06-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0007_auto_20190618_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name_plural': 'Award Organizations'},
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
