# Generated by Django 2.2.2 on 2019-06-24 08:02

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0008_auto_20190619_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietvshow',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='images/movie_tvshows/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='images/people/'),
        ),
    ]
